### PR TITLE
Update "default user roles" with images

### PR DESCRIPTION
**Pull request by sairina**
### Summary
Updated [Default User Roles](https://kolibri.readthedocs.io/en/latest/manage/user_roles.html) with images. So that the docs can visually align the user capabilities with the current UI.

#### For example:
| Before | After |
|--|--|
|Screen Shot 2020-12-28 at 2 01 29 PM| Screen Shot 2020-12-28 at 2 00 39 PM|

### CODE REVIEW

**Comment by radinamatic** [comment]
Thank you, Sairina, for you first docs contribution! :100: 

PR is targeting `develop`, but you've added it to the `0.14` milestone. If the changes refer to Kolibri 0.14, please re-target the PR to `release-v0.14.x` branch.

### Images

Remember that RTD is fully responsive, and that some users might read the docs on smaller screens. I believe the tab labels in the screenshot are too small to be read comfortably even on the 100% desktop browser, and even less on mobile screens.

Desktop | Mobile
----- | -----
Selection_022 | Selection_023

Improvement suggestions:

* resize the browser window with Kolibri to as narrow as you can prior to taking the screenshot
* hover the tab label so the background color is activated (you mention the term `tab` in the text, but without the background it's not immediately clear where the _tab_ is in the screenshot)

Selection_024

Selection_026


(_to be continued_ with suggestions around tables/lists)

**Comment by sairina** [comment]
Thanks for the feedback (keep them coming)! Made the following updates:

1. Updated the images so that tabs and text are larger
2. Made sure to hover over a `tab` within each screenshot
3. Checked on 360x640 (MotoG4) screen (see below)

| At 100% viewing on browser | On MotoG4 |
| -- | -- |
|Screen Shot 2020-12-29 at 12 23 29 PM| Screen Shot 2020-12-29 at 12 24 17 PM|

**Comment by radinamatic** [comment]
New images look great, thank you! :100:  

I rewrote the page to remove the tables (plus some other changes), and opened a PR on your branch. If something is unclear ask away, otherwise you can just merge my PR to see the result.

**Comment by sairina** [comment]
Updated with the `superadmin` image. Let me know what else can be improved. Thank you for being so thorough with your comments and feedback!

**Review by radinamatic — APPROVED** [review]
New page with illustrations looks great, I just pointed to 0.14.x branch! :+1: 

Thank you!

**Pull request merged**
