### PR TITLE
Merge 012 #2

### PR DESCRIPTION
**Pull request by indirectlylit**
replaces https://github.com/learningequality/kolibri-docs/pull/120

### CODE REVIEW

**Review by radinamatic — APPROVED** [review]
Looking good, conflicts no more! 👍

**Comment by indirectlylit** [comment]
looks like the build failed, but it's not clear to me why

**Comment by radinamatic** [comment]
For some reason one change in the release branch (file `contact.rst`) is not reflected in this merge.



So the `.. _support:` reference in `contact.rst` remains and conflicts with the `.. _support:` reference in the *new* `_get_support.rst` file.

I have on my todo to audit all the references to for 0.13, but for now you could just overwrite the `contact.rst` in develop with the same from release branch to fix the build. 

And run the `make lint` to make sure no other creeps up 😉

**Comment by indirectlylit** [comment]
updated

**Comment by radinamatic** [comment]
Awesome, merge away! 👍

**Pull request merged**
