### PR TITLE
update icons for 0.15

### PR DESCRIPTION
**Pull request by indirectlylit**
updates from https://github.com/learningequality/kolibri-design-system/pull/270

### CODE REVIEW

**Comment by radinamatic** [comment]
Thank you @indirectlylit!
Could you re-target this to `release-v0.15.x` branch? I have been working on user docs updates there...

**Comment by indirectlylit** [comment]
all set

**Review by radinamatic — APPROVED** [review]
Not sure if I'll be adding these new `Resource categories` icons in the docs, but they sure are pretty 🙂

**Comment by indirectlylit** [comment]
there are some others too e.g. the new Library icon

https://design-system.learningequality.org/icons/#token-library

image


full changes:

https://docs.google.com/document/d/1ahajDGXWR-Pym8ujBSXbXnw_7BOnYsB0O9TubabQRPg/edit

**Pull request merged**
