### PR TITLE
user docs: attempting to merge 0.12.x -> develop

### PR DESCRIPTION
**Pull request by indirectlylit**
addresses merge conflicts:

```
git merge le/release-v0.12.x
Auto-merging docs/manage/_troubleshooting.rst
CONFLICT (content): Merge conflict in docs/manage/_troubleshooting.rst
Auto-merging docs/manage/_reports.rst
Auto-merging docs/learn.rst
Auto-merging docs/install/tutorials/rpi.rst
CONFLICT (content): Merge conflict in docs/install/tutorials/rpi.rst
CONFLICT (modify/delete): docs/install/_rpi.rst deleted in le/release-v0.12.x and modified in HEAD. Version HEAD of docs/install/_rpi.rst left in tree.
Auto-merging docs/conf.py
Automatic merge failed; fix conflicts and then commit the result.
```

Please check the result and make sure that they're correct.

In the future, let's merge to develop _immediately_ after any change to a release branch to prevent conflicts

### CODE REVIEW

**Comment by benjaoming** [comment]
@indirectlylit great yes, one should always merge upwards.. but it's prone to error since PRs sometimes get merged by another than the one who opened, so let's rehearse our routines :)

**Review by benjaoming — CHANGES_REQUESTED** [review]
`docs/manage/_troubleshooting.rst` was moved into `_get_support.rst` and should also be removed on `develop`, adding the changes to `_get_support.rst` instead I suppose.

**Comment by radinamatic** [comment]
> let's merge to develop immediately after any change to a release branch to prevent conflicts

My bad, I always forget to follow up on this... :disappointed: 

This should be good to merge after the `_troubleshooting.rst` is renamed to `_get_support.rst`.

**Comment by indirectlylit** [comment]
I don't think I'm the right person to complete this conflict resolution. Would one of you mind either opening a new merge PR or building off this one to finish the resolution?

**Comment by benjaoming** [comment]
*points at @radinamatic * 

@radinamatic you better not point back at me :)

**Pull request closed without merging**
