### PR TITLE
Update _initial_setup.rst

### PR DESCRIPTION
**Pull request by vansia43**
Minor spelling fix.

### CODE REVIEW

**Comment by vansia43** [comment]
FYI - This is Danielle Vansia one of the applicants from Google Season of Docs. Thanks!

**Comment by radinamatic** [comment]
Hey Danielle @vansia43, thanks for catching this!

Could you re-target this patch to the branch `release-v0.12.x` instead of `develop`? 
It's the current branch that gets built on RTD, so when I approve and merge, the fix will be visible immediately. :slightly_smiling_face:

**Comment by benjaoming** [comment]
image

image

**Comment by vansia43** [comment]
> Hey Danielle @vansia43, thanks for catching this!
> 
> Could you re-target this patch to the branch `release-v0.12.x` instead of `develop`?
> It's the current branch that gets built on RTD, so when I approve and merge, the fix will be visible immediately. 🙂

Perfect! Updated the branch for the PR.

**Comment by benjaoming** [comment]
Github didn't handle that very gracefully :)

**Comment by vansia43** [comment]
I see that. Closed this PR will do directly from correct branch. :)

**Pull request closed without merging**
