### PR TITLE
update the doc for the new log file locations - release 0.12.x

### PR DESCRIPTION
**Pull request by lyw07**
copy of #96 for release 0.12.x branch.

### CODE REVIEW

**Review by radinamatic — APPROVED** [review]
LGTM! :+1:

**Review by benjaoming — DISMISSED** [review]
Sorry I missed something -- are these changes scheduled for 0.12.x? It's IMO not a good idea to change locations of log files in a patch release.

**Comment by lyw07** [comment]
yeah that makes sense to me. the issue is targeted to 0.12.4 initially: https://github.com/learningequality/kolibri/issues/2512, and the PR has been merged to kolibri 0.12.y branch. 
If we decide to make it to 0.13.0, then I think we can make some changes to the branch

**Comment by rtibbles** [comment]
This is the correct branch @lyw07, please do not modify.

**Pull request merged**
