### PR TITLE
Update ubuntu-debian.rst

### PR DESCRIPTION
**Pull request by VedderPradhan**
Just a small grammatical error fixed.

### CODE REVIEW

**Review by radinamatic — APPROVED** [review]
Thank you @VedderPradhan!

**Comment by radinamatic** [comment]
Actually, @VedderPradhan, could you join all your "small gramatical corrections" in one PR (no need to open separate ones for such small changes), and **target the `0.14.x` branch instead of `develop`**?

**Comment by VedderPradhan** [comment]
> Actually, @VedderPradhan, could you join all your "small gramatical corrections" in one PR (no need to open separate ones for such small changes), and **target the `0.14.x` branch instead of `develop`**?

Oops, sorry. Roger that!

**Comment by radinamatic** [comment]
Fixed in #215, closing.

**Pull request closed without merging**
