### PR TITLE
Remove the language CLI command from docs

### PR DESCRIPTION
**Pull request by rtibbles**
Docs update correlated to this PR: https://github.com/learningequality/kolibri/pull/5494 which finally removes the vestigial language command.

### CODE REVIEW

**Comment by indirectlylit** [comment]
this looks fine to me. @radinamatic  any concerns?

**Comment by radinamatic** [comment]
Dang, I've just updated that table in 0.12.7 release docs... 😂 
Give me a heads-up next time @rtibbles when you plan to 💥 entire chunks! 
No concerns otherwise, good to go! 👍

**Comment by rtibbles** [comment]
I mean... the command literally does nothing, so documenting it a mischief!

**Comment by indirectlylit** [comment]
if it literally does nothing, can we target this to the 0.12.x branch and avoid some merge conflicts?

**Comment by rtibbles** [comment]
OK, going to close this PR and make the change on release-v0.12.x instead.

**Pull request closed without merging**
